# Generated by Django 5.1.7 on 2025-03-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
